name: unotest
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  provider: ^6.0.2

  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6

  equatable: ^2.0.3

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.0.3+1
  mockito: ^5.1.0
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true